export const TOGGLE_DETAIL_VIEW = 'TOGGLE_DETAIL_VIEW';
export const MODIFY_SCHEDULE = 'MODIFY_SCHEDULE';
export const POPULATE_SCHEDULE = 'POPULATE_SCHEDULE';
export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
